import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {
  geistMono,
  geistSans,
  momoSignature,
  outfit,
  playwriteNZ,
} from "@/lib/fonts";
import { ThemeProvider } from "@/components/provides/ThemeProvider";

export const metadata: Metadata = {
  title: "ShadcnCart. E-COMMERCE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${momoSignature.variable}
          ${playwriteNZ.variable}
          ${outfit.variable}
          ${outfit.className}
          antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto px-1 sm:px-10 sm:max-w-xl md:max-w-2xl xl:max-w-6xl m-4 mb-15">
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
